#!/usr/bin/env bun

const fs = require('fs');
const path = require('path');

const commands = {
  'generate:page': generatePage,
  'generate:component': generateComponent,
  'add:route': addRoute,
  'help': showHelp,
};

function generatePage(name) {
  if (!name) {
    console.error('❌ Error: Page name is required');
    console.log('Usage: bun run cli generate:page <PageName>');
    return;
  }

  const pagePath = path.join(process.cwd(), 'src', 'pages', `${name}.tsx`);

  if (fs.existsSync(pagePath)) {
    console.error(`❌ Error: Page ${name} already exists`);
    return;
  }

  const template = `export function ${name}() {
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-3xl font-bold">${name}</h1>
      <p>Generated by Frontend CLI</p>
    </div>
  );
}
`;

  fs.mkdirSync(path.dirname(pagePath), { recursive: true });
  fs.writeFileSync(pagePath, template);
  console.log(`✅ Page created: ${pagePath}`);
}

function generateComponent(name) {
  if (!name) {
    console.error('❌ Error: Component name is required');
    console.log('Usage: bun run cli generate:component <ComponentName>');
    return;
  }

  const componentPath = path.join(process.cwd(), 'src', 'components', `${name}.tsx`);

  if (fs.existsSync(componentPath)) {
    console.error(`❌ Error: Component ${name} already exists`);
    return;
  }

  const template = `interface ${name}Props {
  // Add props here
}

export function ${name}({}: ${name}Props) {
  return (
    <div>
      <h2>${name}</h2>
    </div>
  );
}
`;

  fs.mkdirSync(path.dirname(componentPath), { recursive: true });
  fs.writeFileSync(componentPath, template);
  console.log(`✅ Component created: ${componentPath}`);
}

function addRoute(pageName) {
  console.log(`📝 To add route for ${pageName}:`);
  console.log(`
1. Import: import { ${pageName} } from './pages/${pageName}';
2. Add Route: <Route path="/${pageName.toLowerCase()}" element={<${pageName} />} />
  `);
}

function showHelp() {
  console.log(`
🛠️  Frontend CLI - Micro-Frontend Tooling

Available Commands:
  generate:page <PageName>       - Generate a new page
  generate:component <Name>      - Generate a new component
  add:route <PageName>           - Show instructions to add route
  help                           - Show this help message

Examples:
  bun run cli generate:page Dashboard
  bun run cli generate:component UserCard
  bun run cli add:route Dashboard
  `);
}

// Main execution
const [, , command, ...args] = process.argv;

if (!command || !commands[command]) {
  console.error('❌ Unknown command');
  showHelp();
  process.exit(1);
}

commands[command](...args);
