#!/usr/bin/env bun

const fs = require('fs');
const path = require('path');

const commands = {
  'generate:page': generatePage,
  'generate:component': generateComponent,
  'add:route': addRoute,
  'expose:module': exposeModule,
  'help': showHelp,
};

function generatePage(name) {
  if (!name) {
    console.error('❌ Error: Page name is required');
    console.log('Usage: bun run cli generate:page <PageName>');
    return;
  }

  const pagePath = path.join(process.cwd(), 'apps', 'web', 'src', 'pages', `${name}.tsx`);

  if (fs.existsSync(pagePath)) {
    console.error(`❌ Error: Page ${name} already exists at ${pagePath}`);
    return;
  }

  const template = `import { useAuth } from '@sdk-repo/sdk/hooks';
import {
    Card,
    CardHeader,
    CardTitle,
    CardDescription,
    CardContent,
    Button,
} from '@sdk-repo/sdk/components';

export function ${name}() {
    const { user, hasPermission } = useAuth();

    return (
        <div className="container mx-auto p-6 max-w-7xl">
            <div className="mb-6">
                <h1 className="text-3xl font-bold text-foreground">${name}</h1>
                <p className="text-muted-foreground mt-1">
                    Generated by Frontend CLI
                </p>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>${name} Content</CardTitle>
                    <CardDescription>
                        Add your content here. Logged in as {user?.name} ({user?.role})
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">
                        Start building your page here.
                    </p>
                </CardContent>
            </Card>
        </div>
    );
}
`;

  fs.mkdirSync(path.dirname(pagePath), { recursive: true });
  fs.writeFileSync(pagePath, template);
  console.log(`✅ Page created: ${pagePath}`);
  console.log(`\n📝 Next steps:`);
  console.log(`   1. Add route: bun run cli add:route ${name}`);
  console.log(`   2. Expose via federation: bun run cli expose:module ${name}`);
}

function generateComponent(name) {
  if (!name) {
    console.error('❌ Error: Component name is required');
    console.log('Usage: bun run cli generate:component <ComponentName>');
    return;
  }

  const componentPath = path.join(process.cwd(), 'apps', 'web', 'src', 'components', `${name}.tsx`);

  if (fs.existsSync(componentPath)) {
    console.error(`❌ Error: Component ${name} already exists`);
    return;
  }

  const template = `import { memo } from 'react';

interface ${name}Props {
    // Add props here
}

export const ${name} = memo(function ${name}({}: ${name}Props) {
    return (
        <div className="p-4">
            <h2 className="text-lg font-semibold text-foreground">${name}</h2>
            <p className="text-muted-foreground text-sm">Component content here.</p>
        </div>
    );
});
`;

  fs.mkdirSync(path.dirname(componentPath), { recursive: true });
  fs.writeFileSync(componentPath, template);
  console.log(`✅ Component created: ${componentPath}`);
}

function addRoute(pageName) {
  if (!pageName) {
    console.error('❌ Error: Page name is required');
    console.log('Usage: bun run cli add:route <PageName>');
    return;
  }

  const appPath = path.join(process.cwd(), 'apps', 'web', 'src', 'App.tsx');

  if (!fs.existsSync(appPath)) {
    console.log(`📝 To add route for ${pageName} manually:`);
    console.log(`   1. Import: import { ${pageName} } from './pages/${pageName}';`);
    console.log(`   2. Add Route: <Route path="/${pageName.toLowerCase()}" element={<${pageName} />} />`);
    return;
  }

  let content = fs.readFileSync(appPath, 'utf-8');

  // Check if route already exists
  if (content.includes(`/${pageName.toLowerCase()}`)) {
    console.log(`⚠️  Route "/${pageName.toLowerCase()}" already exists in App.tsx`);
    return;
  }

  // Add import
  const importLine = `import { ${pageName} } from "./pages/${pageName}";`;
  const lastImportIdx = content.lastIndexOf('import ');
  const lineEnd = content.indexOf('\n', lastImportIdx);
  content = content.slice(0, lineEnd + 1) + importLine + '\n' + content.slice(lineEnd + 1);

  // Add route before the last </Routes>
  const routeLine = `                <Route path="/${pageName.toLowerCase()}" element={<${pageName} />} />`;
  const routesCloseIdx = content.lastIndexOf('</Routes>');
  content = content.slice(0, routesCloseIdx) + routeLine + '\n                ' + content.slice(routesCloseIdx);

  fs.writeFileSync(appPath, content);
  console.log(`✅ Route added: /${pageName.toLowerCase()} -> ${pageName}`);
  console.log(`   Import and Route both added to App.tsx`);
}

function exposeModule(moduleName) {
  if (!moduleName) {
    console.error('❌ Error: Module name is required');
    console.log('Usage: bun run cli expose:module <ModuleName>');
    return;
  }

  // Create the expose wrapper file
  const exposePath = path.join(process.cwd(), 'apps', 'web', 'src', 'pages', `${moduleName}Expose.tsx`);

  if (!fs.existsSync(exposePath)) {
    const exposeTemplate = `// Federation wrapper — ensures CSS is bundled with the module
import '../index.css';
import '@sdk-repo/sdk/styles.css';

export { ${moduleName} } from './${moduleName}';
`;
    fs.mkdirSync(path.dirname(exposePath), { recursive: true });
    fs.writeFileSync(exposePath, exposeTemplate);
    console.log(`✅ Expose wrapper created: ${exposePath}`);
  } else {
    console.log(`ℹ️  Expose wrapper already exists: ${exposePath}`);
  }

  // Update webpack.config.js
  const configPath = path.join(process.cwd(), 'apps', 'web', 'webpack.config.js');

  if (!fs.existsSync(configPath)) {
    console.error('❌ webpack.config.js not found');
    console.log(`   Manually add to exposes: './${moduleName}': './src/pages/${moduleName}Expose.tsx'`);
    return;
  }

  let config = fs.readFileSync(configPath, 'utf-8');

  if (config.includes(`./${moduleName}`)) {
    console.log(`⚠️  Module "./${moduleName}" is already exposed in webpack config`);
    return;
  }

  const exposesRegex = /(exposes:\s*\{)/;
  if (exposesRegex.test(config)) {
    const newExpose = `'./${moduleName}': './src/pages/${moduleName}Expose.tsx',`;
    config = config.replace(exposesRegex, `$1\n        ${newExpose}`);
    fs.writeFileSync(configPath, config);
    console.log(`✅ Module Federation updated: ./${moduleName} -> ${moduleName}Expose.tsx`);
  } else {
    console.error('❌ Could not find exposes config in webpack.config.js');
    console.log(`   Manually add: './${moduleName}': './src/pages/${moduleName}Expose.tsx'`);
  }

  // Remind about host app
  console.log(`\n📝 Don't forget to update the Host App:`);
  console.log(`   1. Add remote type declaration in apps/host/src/types/remotes.d.ts`);
  console.log(`   2. Import and lazy-load in the Host App's routing`);
}

function showHelp() {
  console.log(`
🛠️  Frontend CLI — Micro-Frontend Platform Tooling

Available Commands:

  generate:page <PageName>         Generate a new page with SDK integration
  generate:component <Name>        Generate a new React component
  add:route <PageName>             Add route to App.tsx automatically
  expose:module <ModuleName>       Expose module via Module Federation
  help                             Show this help message

Examples:

  bun run cli generate:page Settings
  bun run cli generate:component UserCard
  bun run cli add:route Settings
  bun run cli expose:module Settings
  `);
}

// ─── Main Execution ─────────────────────────────────────────────────────────────

const [, , command, ...args] = process.argv;

if (!command || !commands[command]) {
  console.error('❌ Unknown command:', command || '(none)');
  showHelp();
  process.exit(1);
}

commands[command](...args);
